# Metadata about this component, to be used in the CMS
spec:
  structures:
    - content_blocks
  label: Feature
  description: Feature section
  icon: "stars"
  tags: []

# Defines the structure of this component, as well as the default values
blueprint:
  image_path: /images/feature/feature-card-one.png
  title: Simply click and send
  description: Make your message stand out, thanks to the guided copywriting and design features, triggering a positive response from your customers.
  btn:
    link: /#
    text: Try Free
  reversed: false

# Overrides any fields in the blueprint when viewing this component in the component browser
preview:

# Any extra CloudCannon inputs configuration to apply to the blueprint
_inputs: 
  description:
    type: markdown
  image:
    type: image
    options:
      width: 696
      height: 752
      resize_style: crop