# Metadata about this component, to be used in the CMS
spec:
  structures:
    - content_blocks
  label: Pricing Table
  description: Pricing table section
  icon: "table_rows"
  tags: []

# Defines the structure of this component, as well as the default values
blueprint:
  pricing_tier:
    - tier: free
      description: Everything you need to get started.
      price: 0
      hasDiscount: false
      discountPrice: 0
      isActive: false
      feature:
      btn:
        link: /#
        text: Try This Free

# Overrides any fields in the blueprint when viewing this component in the component browser
preview:

# Any extra CloudCannon inputs configuration to apply to the blueprint
_inputs: 
  feature:
    type: array
    options:
      structures: _structures.features