# Metadata about this component, to be used in the CMS
spec:
  structures:
    - content_blocks
  label: About Hero
  description: About Hero section
  icon: "apps"
  tags: ["hero"]

# Defines the structure of this component, as well as the default values
blueprint:
  title: On a mission to change email marketing
  description: We’re here to breathe new air into email marketing and help grow your business.
  hero_images:
    - image_path: /images/about/aboutfeature-three.jpg
      placer: front_bottom
  link:
    text: "Try Free"
    url: "/#"

# Overrides any fields in the blueprint when viewing this component in the component browser
preview:


# Any extra CloudCannon inputs configuration to apply to the blueprint
_inputs:
  placer:
    type: select
    options:
      values:
        - front_bottom
        - back_top_right
        - back_top_left
  image:
    type: image
    options:
      width: 450
      height: 450
      resize_style: crop